version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "vitalijprokopenya"
      POSTGRES_PASSWORD: "1234"
    ports:
        - "5431:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
