version: '3.5'

services:
  crud:
    restart: always
    image: crud
    ports:
      - "1323:1323"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      POSTGRES_HOST: "postgres"
      REDIS_ADDR: "redis:6379"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "vitalijprokopenya"
      POSTGRES_PASSWORD: "1234"
    ports:
        - "5431:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
