// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/HekapOo-hub/Task1/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// HumanCacheRepository is an autogenerated mock type for the HumanCacheRepository type
type HumanCacheRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: h
func (_m *HumanCacheRepository) Create(h model.Human) error {
	ret := _m.Called(h)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Human) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: name
func (_m *HumanCacheRepository) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: name
func (_m *HumanCacheRepository) Get(name string) (*model.Human, error) {
	ret := _m.Called(name)

	var r0 *model.Human
	if rf, ok := ret.Get(0).(func(string) *model.Human); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Human)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
